version: "3.8"
volumes:
  redis-data: {}
  mysqldb : {}

services:  
  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD" ,"--appendonly", "yes"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tour
      MYSQL_USER: zoom
      MYSQL_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldb:/var/lib/mysql
      - ./sql/initdb.d:/docker-entrypoint-initdb.d
